"""empty message

Revision ID: ec9bf3ed2bdc
Revises: 
Create Date: 2021-05-03 16:08:30.236868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9bf3ed2bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'interviews', ['interview_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'interview_id')
    # ### end Alembic commands ###
